# Generated by Django 5.2.4 on 2025-07-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('CU', 'Customer'), ('VE', 'Vendor'), ('AD', 'Admin')], default='CU', max_length=20),
        ),
    ]
